ARG BACKEND_IMAGE_NAME
ARG BACKEND_IMAGE_TAG

FROM ${BACKEND_IMAGE_NAME}:${BACKEND_IMAGE_TAG} AS backend

FROM nginx:1.22.1-alpine AS nginx

COPY --from=backend /app/static /app/static
COPY ./docker/nginx-site.conf /etc/nginx/conf.d/default.conf

WORKDIR /
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 80
