version: "3.5"

services:
  postgis_test:
    image: postgis/postgis:14-3.2
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
    env_file: ../.env
  backend_test:
    image: freeyeti/dev-in-docker:python3.10-poetry1.3.1-gdal-dev
    env_file: ../.env
    environment:
      - DB_HOST=postgis_test
      - DJANGO_SETTINGS_MODULE=app.settings_test
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ../:/code
      - ../tmp/data:/data
      - ../tmp/cache/pypoetry:/root/.cache/pypoetry
    depends_on:
      - postgis_test
