version: "3.5"

services:
  postgis:
    image: postgis/postgis:14-3.2
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - freeyeti-backend-postgisdb:/var/lib/postgresql/data
    env_file: ../.env
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "0.0.0.0:8001:80"
    env_file: ../.env
    volumes:
      - ./pgadmin4-servers.json:/pgadmin4/servers.json
  backend:
    image: docker.io/freeyeti/dev-in-docker:python3.10-poetry1.4.0-gdal-dev
    container_name: backend-dev-container
    env_file: ../.env
    environment:
      - IN_CONTAINER=yes
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ../:/code
      - ../tmp/data:/data
      - freeyeti-backend-pypoetrycache:/root/.cache/pypoetry
    depends_on:
      - postgis
      - pgadmin

volumes:
  freeyeti-backend-pypoetrycache:
  freeyeti-backend-postgisdb: