version: "3.5"

services:
  postgis_test:
    image: postgis/postgis:14-3.2
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - postgisdb:/var/lib/postgresql/data
    env_file: ../.env
  backend_test:
    image: docker.io/freeyeti/dev-in-docker:python3.11-poetry1.5.1-gdal-dev
    env_file: ../.env
    environment:
      - DB_HOST=postgis_test
      - DJANGO_SETTINGS_MODULE=app.settings.test
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ../:/code
      - ../tmp/data:/data
    depends_on:
      - postgis_test

volumes:
  postgisdb:
