# Generated by Django 4.2.8 on 2024-01-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage_view_count_lifeblogpage_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='view_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lifeblogpage',
            name='view_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
