# Generated by Django 4.2.4 on 2023-11-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yechat', '0002_alter_chatroom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
