# Generated by Django 4.2.4 on 2023-08-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='url',
        ),
        migrations.AddField(
            model_name='watch',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
