name: release

on:
  release:
    types: [published]

env:
  # Define image names
  BACKEND_IMAGE: ghcr.io/jianxuan-li/freeyeti-backend
  REGISTRY: ghcr.io


jobs:
  config:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
        
      - name: Check output
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.ref_name }} > version.txt
          
      - name: Upload version file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-deployment
          path: version.txt

  # Build and push image to Docker registry.
  build:
    # Ensure config job passes before building image.
    needs: config

    runs-on: [ubuntu-latest]

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check image version
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          echo $IMAGE_TAG
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ## Generate deployment files.
  generate-artifacts:
    # Ensure django image is built before run testing.
    needs: build

    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          
      - name: Check image version
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          echo $IMAGE_TAG
      - name: Generate deployment files
        env:
          IMAGE_TAG: ${{ github.ref_name }}
          WWW_DATA_PATH: ${{ secrets.WWW_DATA_PATH }}
          PULL_SECRET: ${{ secrets.PULL_SECRET }}
        run: |
          sed -i "s@__IMAGE_BACKEND__@$BACKEND_IMAGE@g" k8s/deployment.yaml
          sed -i "s@__IMAGE_TAG__@$IMAGE_TAG@g" k8s/deployment.yaml
          sed -i "s@__WWW_DATA_PATH__@$WWW_DATA_PATH@g" k8s/deployment.yaml
          sed -i "s@__PULL_SECRET__@$PULL_SECRET@g" k8s/deployment.yaml
          sed -i "s@__IMAGE_BACKEND__@$BACKEND_IMAGE@g" k8s/job.db-migrate.yaml
          sed -i "s@__IMAGE_TAG__@$IMAGE_TAG@g" k8s/job.db-migrate.yaml
          sed -i "s@__PULL_SECRET__@$PULL_SECRET@g" k8s/job.db-migrate.yaml
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-deployment
          path: |
            k8s/config-map.yaml
            k8s/deployment.yaml
            k8s/job.db-migrate.yaml
            k8s/service.backend.yaml
  deploy:
    needs: generate-artifacts

    runs-on: [self-hosted]

    steps:
      - name: download deployment files
        uses: actions/download-artifact@v3
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        with:
          name: ${{ github.event.repository.name }}-deployment
          path: /root/deployment/freeyeti/${{ github.ref_name }}

      - name: deploy
        working-directory: /root/deployment/freeyeti/${{ github.ref_name }}
        run: |
          kubectl apply -f config-map.yaml
          kubectl delete -f job.db-migrate.yaml || echo "Database migration job is not exists"
          kubectl apply -f job.db-migrate.yaml
          kubectl wait --timeout=300s --for=condition=complete jobs/freeyeti-backend-db-migrate
          kubectl logs -f jobs/freeyeti-backend-db-migrate
          kubectl delete -f job.db-migrate.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.backend.yaml